import {chromium,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const art=resolve('artifacts/browser');await mkdir(art,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
const fixture=await readFile('test/fixtures/expanded-native.ardour'),fractional=await readFile('test/fixtures/fractional-native.ardour'),shipped=await readFile('dist/beat-courier.html');
expect(sha(fixture)).toBe('f84c16e8f167fc5f351ee584e2dbd92f9459dff25874a71d7036c926b1509829');expect(sha(fractional)).toBe('2844ac587dcfbd2c94aa572a32863c2f53bffca32c9d97872acacb6b2d8aadb8');
const expected=Buffer.from('4d546864000000060000000107804d54726b0000005400ff510307a12000ff580404021808f800ff51030927c000ff580403021808da00ff51030c350000ff5804070318089e00ff510307a120bc00ff510307717df800ff5103061a8000ff5804040218088f00ff2f00','hex');
const positions=[['tempo','0','0'],['meter','0','0'],['tempo','8','15360'],['meter','8','15360'],['tempo','14','26880'],['meter','14','26880'],['tempo','16','30720'],['tempo','20','38400'],['tempo','28','53760'],['meter','28','53760']];
const report={status:'RUNNING',cases:[],rejections:[],pageErrors:[],consoleErrors:[],networkRequests:[],workerURLs:[],screenshots:[],shippedHTMLSHA256:sha(shipped),downloads:{}};
const check=(name,extra={})=>{report.cases.push({name,passed:true,...extra});console.log('PASS',name);};
if(!process.env.CHROMIUM_PATH)throw Error('Use the hosted sandboxed Chrome');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,chromiumSandbox:true});report.browserVersion=browser.version();
const commands=execFileSync('ps',['-eo','args'],{encoding:'utf8'}).split('\n').filter(s=>s.includes('--remote-debugging-pipe')&&s.includes('--user-data-dir=')&&/chrome|chromium/.test(s));expect(commands.length).toBeGreaterThan(0);expect(commands.some(s=>s.includes('--no-sandbox')||s.includes('--disable-setuid-sandbox'))).toBe(false);report.chromiumMainProcessCommands=commands;
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});await context.setOffline(true);const page=await context.newPage();let downloads=0;
function track(p){p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('request',r=>{if(/^https?:/.test(r.url()))report.networkRequests.push(r.url());});p.on('worker',w=>report.workerURLs.push(w.url()));p.on('download',()=>downloads++);}
track(page);
const payload=(buffer=fixture,name='private-session.ardour')=>({buffer,name,mimeType:'application/xml'});
async function load(buffer=fixture,name='private-session.ardour'){await page.locator('#session-file').setInputFiles(payload(buffer,name));await expect(page.locator('#status')).not.toContainText(/Reading|Preparing|読み込んで|別スレッド/,{timeout:12000});}
async function ready(){await expect(page.locator('#rows tr')).toHaveCount(10);await expect(page.locator('#confirm')).toBeEnabled();await expect(page.locator('#cancel')).toBeHidden();}
async function approve(){await page.locator('#confirm').check();await expect(page.locator('#export')).toBeEnabled();}
async function save(selector,name,keyboard=false){const event=page.waitForEvent('download');if(keyboard){await page.locator(selector).focus();await page.keyboard.press('Enter');}else await page.locator(selector).click();const d=await event;await d.saveAs(resolve(art,name));return readFile(resolve(art,name));}
async function shot(name,locator=page){await locator.screenshot({path:resolve(art,name),...(locator===page?{fullPage:true}:{})});report.screenshots.push(name);}
try{
 await page.goto(pathToFileURL(resolve('dist/beat-courier.html')).href);await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('h1')).toHaveText('テンポの変化を、\n次のセッションへ。');await expect(page.locator('#choose')).toHaveText('セッションファイルを選ぶ');await expect(page.locator('#status')).toContainText('保存済みのセッション');await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();check('Initialized Japanese UI renders its labels with no input, review or export');
 const chooser=page.waitForEvent('filechooser');await page.locator('#choose').focus();await page.keyboard.press('Enter');await (await chooser).setFiles(payload());await ready();await expect(page.locator('#session-file')).toHaveValue('');await expect(page.locator('#file-meta')).toContainText('private-session.ardour');await expect(page.locator('#export')).toBeDisabled();check('Real keyboard chooser imports into a worker and clears native file input for reselection');
 expect(await page.locator('#rows tr').evaluateAll(rows=>rows.map(n=>[n.dataset.kind,n.dataset.quarter,n.cells[1].textContent]))).toEqual(positions);await expect(page.locator('#tempo-count')).toHaveText('6');await expect(page.locator('#meter-count')).toHaveText('4');await expect(page.locator('#rounded-count')).toHaveText('1');await expect(page.locator('tr.tempo[data-quarter="14"]')).toContainText('150');await expect(page.locator('tr.tempo[data-quarter="14"]')).toContainText('1/8');await expect(page.locator('tr.tempo[data-quarter="14"]')).toContainText('800000 µs');check('Every literal position, tick, source eighth-note unit and changed meter is visible');
 await expect(page.locator('tr.tempo[data-quarter="14"] td:nth-child(5)')).toContainText('75 ♩ / min');await page.locator('.exact summary').click();await expect(page.locator('.exact code')).toHaveText('49681122359305/409999999346301');check('Eighth-note conversion shows75 quarter notes/minute and rounded tempo exposes its exact rational error');
 await page.locator('#confirm').focus();await page.keyboard.press('Space');const midi=await save('#export','conductor.mid',true);expect(midi.equals(expected)).toBe(true);const receiptBytes=await save('#receipt','receipt.json'),receipt=JSON.parse(receiptBytes);
 expect(receipt.tool).toBe('BeatCourier');expect(receipt.exportOrigin).toBe('browser UI download');expect(receipt.sourceFile).toEqual({name:'private-session.ardour',bytes:fixture.length});expect(receipt.sourceSha256).toBe(sha(fixture));expect(receipt.outputSha256).toBe(sha(midi));expect(receipt.outputBytes).toBe(106);expect(receipt.ppqn).toBe(1920);expect(receipt.endTick).toBe('55680');expect(receipt.noteEvents).toBe(0);
 expect(receipt.review.map(r=>[r.kind,r.quarter,r.tick])).toEqual(positions);expect(receipt.review.filter(r=>r.kind==='tempo').map(r=>r.microseconds)).toEqual([500000,600000,800000,500000,487805,400000]);expect(receipt.review.filter(r=>r.kind==='meter').map(r=>[r.numerator,r.denominator,r.clocksPerClick,r.notated32nds])).toEqual([[4,4,24,8],[3,4,24,8],[7,8,24,8],[4,4,24,8]]);
 expect(receipt.review.find(r=>r.quarter==='20')).toEqual({kind:'tempo',quarter:'20',tick:'38400',microseconds:487805,exactMicroseconds:'200000000000000000000/409999999346301',errorMicroseconds:'49681122359305/409999999346301',sourceQuarterNotesPerMinute:'1229999998038903/10000000000000',midiQuarterNotesPerMinute:'12000000/97561',rounded:true});
 report.downloads.primary={sha256:sha(midi),bytes:midi.length,receiptSHA256:sha(receiptBytes)};await writeFile(resolve(art,'source-input.ardour'),fixture);await writeFile(resolve(art,'fractional-input.ardour'),fractional);check('Actual keyboard MIDI and receipt downloads match independent literal wire and exact rounding');
 expect((await save('#export','repeated-conductor.mid')).equals(midi)).toBe(true);expect((await save('#receipt','repeated-receipt.json')).equals(receiptBytes)).toBe(true);check('Repeated downloads preserve exact MIDI and receipt bytes');
 const again=page.waitForEvent('filechooser');await page.locator('#choose').focus();await page.keyboard.press('Enter');await (await again).setFiles(payload());await ready();await expect(page.locator('#confirm')).not.toBeChecked();await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();check('Choosing the same file again invalidates approval and previous receipt');
 for(const lang of ['ja','en']){
  await page.locator('#lang-'+lang).click();await expect(page.locator('html')).toHaveAttribute('lang',lang);await expect(page.locator('#confirm')).not.toBeChecked();await page.locator('#lang-'+lang).hover();const contrast=await page.locator('#lang-'+lang).evaluate(e=>{const s=getComputedStyle(e),lum=color=>{const c=color.match(/[0-9.]+/g).slice(0,3).map(v=>Number(v)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;},a=lum(s.color),b=lum(s.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);});expect(contrast).toBeGreaterThanOrEqual(4.5);check(`${lang} selected-language hover retains readable contrast`,{contrast});await shot(`01-${lang}-desktop.png`);await approve();
  await page.emulateMedia({media:'print'});expect(await page.evaluate(()=>getComputedStyle(document.documentElement).backgroundColor)).toBe('rgb(255, 255, 255)');await page.emulateMedia({media:'screen'});await page.pdf({path:resolve(art,`02-${lang}-review.pdf`),format:'A4',printBackground:true});const txt=execFileSync('pdftotext',[resolve(art,`02-${lang}-review.pdf`),'-'],{encoding:'utf8'});for(const token of ['BeatCourier','private-session.ardour','500000','600000','800000','487805','400000','7/8','49681122359305/409999999346301'])expect(txt.replace(/\s+/g,'')).toContain(token.replace(/\s+/g,''));expect(txt.split('\n').some(line=>line.includes('122.999969')&&line.includes('min'))).toBe(true);const info=execFileSync('pdfinfo',[resolve(art,`02-${lang}-review.pdf`)],{encoding:'utf8'}),pages=Number(/Pages:\s+(\d+)/.exec(info)[1]);expect(pages).toBeLessThanOrEqual(2);execFileSync('pdftoppm',['-scale-to','1400','-png',resolve(art,`02-${lang}-review.pdf`),resolve(art,`02-${lang}-review`)]);check(`${lang} print preserves every map value and exact rounding fraction`,{pages});
  for(const width of [390,320]){
   await page.setViewportSize({width,height:900});await page.locator('.table-wrap').evaluate(e=>e.scrollLeft=0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(`03-${lang}-${width}-left.png`);
   await page.locator('.table-wrap').evaluate(e=>e.scrollLeft=e.scrollWidth);const b=await page.locator('.table-wrap').evaluate(e=>{const r=e.getBoundingClientRect(),h=e.querySelector('th:last-child').getBoundingClientRect(),c=e.querySelector('tr.tempo[data-quarter="20"] td:last-child').getBoundingClientRect();return {left:r.left,right:r.right,headerLeft:h.left,headerRight:h.right,cellLeft:c.left,cellRight:c.right,scroll:e.scrollLeft};});expect(b.scroll).toBeGreaterThan(0);expect(b.headerLeft).toBeGreaterThanOrEqual(b.left-2);expect(b.headerRight).toBeLessThanOrEqual(b.right+2);expect(b.cellLeft).toBeGreaterThanOrEqual(b.left-2);expect(b.cellRight).toBeLessThanOrEqual(b.right+2);await shot(`03-${lang}-${width}-right.png`,page.locator('#review'));check(`${lang} ${width}px has no page overflow and the full rounding column is reachable`,b);
  }
  await page.setViewportSize({width:1440,height:1100});await page.locator('.table-wrap').evaluate(e=>e.scrollLeft=0);
 }
 await page.locator('#confirm').uncheck();await expect(page.locator('#receipt')).toBeDisabled();await expect(page.locator('#export')).toBeDisabled();check('Removing confirmation invalidates the prior receipt');
 await page.locator('#session-file').evaluate(e=>{e.value='';e.dispatchEvent(new Event('change',{bubbles:true}));});await expect(page.locator('#rows tr')).toHaveCount(0);await expect(page.locator('#confirm')).toBeDisabled();check('Dispatched empty file change clears review and output');
 const raw=fixture.toString('utf8'),mutate=(a,b)=>{expect(raw).toContain(a);return Buffer.from(raw.replace(a,b));};
 const bads=[['native fractional15.5',fractional,'FRACTIONAL_POSITION'],['ramp endpoint',mutate('enpm="100"','enpm="110"'),'RAMP'],['ramp omega',mutate('omega="0"','omega="0.1"'),'RAMP'],['BBT reset',mutate('<MusicTimes/>','<MusicTimes><MusicTime name="reset"/></MusicTimes>'),'MAP_STRUCTURE'],['corrupt BBT',mutate('bbt="3|1|0"','bbt="3|2|0"'),'MAP_BBT'],['tempo range',mutate('npm="100" enpm="100"','npm="1" enpm="1"'),'TEMPO_RANGE'],['DTD',Buffer.from('<!DOCTYPE Session SYSTEM "https://example.invalid/x"><Session/>'),'XML_DOCTYPE'],['bad UTF8',Buffer.from([255,255]),'XML_ENCODING'],['old schema',mutate('version="7003"','version="7002"'),'SESSION_VERSION'],['full-bound malformed XML',Buffer.alloc(4*1024*1024,60),'INVALID_XML'],['oversize',Buffer.alloc(4*1024*1024+1,32),'INPUT_LIMIT']];
 for(const [name,buffer,code] of bads){await load();await ready();await approve();const before=downloads;await load(buffer,'unsupported.ardour');await expect(page.locator('#error')).toContainText(code);await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();await expect(page.locator('#rows tr')).toHaveCount(0);expect(downloads).toBe(before);report.rejections.push({name,code,sha256:sha(buffer),outputCreated:false});check(`${name} rejects and cannot retain the old output`);}
 await shot('04-en-error.png');
 const tiny=mutate('npm="120" enpm="120"','npm="120.000000000001" enpm="120.000000000001"');await load(tiny);await ready();await expect(page.locator('tr.tempo[data-quarter="0"] td:last-child')).toContainText('0 < Δ < 0.000001');await page.locator('tr.tempo[data-quarter="0"] .exact summary').click();expect(await page.locator('tr.tempo[data-quarter="0"] .exact code').textContent()).not.toBe('0');check('Subprecision nonzero tempo rounding shows a signed bound and exact fraction, never zero');
 await load(fixture,'<img src=x onerror=alert(1)>.ardour');await ready();await expect(page.locator('#file-meta')).toContainText('<img src=x onerror=alert(1)>');expect(await page.locator('img').count()).toBe(0);check('Chosen filename is rendered as inert text');
 await page.evaluate(()=>{window.originalRead=File.prototype.arrayBuffer;window.pendingReads=0;window.readWaits=[];File.prototype.arrayBuffer=async function(){if(this.name==='slow.ardour'){window.pendingReads++;await new Promise(r=>window.readWaits.push(r));try{return await window.originalRead.call(this);}finally{window.pendingReads--;}}return window.originalRead.call(this);};});
 await page.locator('#session-file').setInputFiles(payload(fixture,'slow.ardour'));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(1);await page.locator('#reset').click();await page.evaluate(()=>window.readWaits.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(0);await expect(page.locator('#rows tr')).toHaveCount(0);check('Clearing during a paused File read prevents stale review');
 await page.locator('#session-file').setInputFiles(payload(fixture,'slow.ardour'));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(1);await load(fractional,'newer.ardour');await expect(page.locator('#error')).toContainText('FRACTIONAL_POSITION');await page.evaluate(()=>window.readWaits.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingReads)).toBe(0);await expect(page.locator('#error')).toContainText('FRACTIONAL_POSITION');await expect(page.locator('#rows tr')).toHaveCount(0);await page.evaluate(()=>File.prototype.arrayBuffer=window.originalRead);check('A later unsupported file wins over a delayed earlier valid read');
 await page.evaluate(()=>{window.NativeWorker=Worker;window.workerQueue=[];window.terminatedWorkers=0;window.pendingPosts=0;window.delayWorkers=true;window.Worker=function(...args){const worker=new window.NativeWorker(...args),post=worker.postMessage.bind(worker),terminate=worker.terminate.bind(worker);worker.postMessage=(...data)=>{if(window.delayWorkers){window.pendingPosts++;window.workerQueue.push(()=>{post(...data);window.pendingPosts--;});}else post(...data);};worker.terminate=()=>{window.terminatedWorkers++;terminate();};return worker;};});
 await page.locator('#session-file').setInputFiles(payload());await expect.poll(()=>page.evaluate(()=>window.pendingPosts)).toBe(1);await expect(page.locator('#cancel')).toBeEnabled();await page.locator('#cancel').focus();await page.keyboard.press('Enter');expect(await page.evaluate(()=>window.terminatedWorkers)).toBe(1);await page.evaluate(()=>window.workerQueue.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingPosts)).toBe(0);await expect(page.locator('#rows tr')).toHaveCount(0);await expect(page.locator('#export')).toBeDisabled();check('Keyboard cancellation terminates a paused worker and cannot resurrect its result');
 await page.locator('#session-file').setInputFiles(payload());await expect.poll(()=>page.evaluate(()=>window.pendingPosts)).toBe(1);await expect(page.locator('#error')).toContainText('TIMEOUT',{timeout:12000});expect(await page.evaluate(()=>window.terminatedWorkers)).toBe(2);await page.evaluate(()=>window.workerQueue.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingPosts)).toBe(0);await expect(page.locator('#rows tr')).toHaveCount(0);await page.evaluate(()=>{window.Worker=window.NativeWorker;window.delayWorkers=false;});check('Bounded worker timeout blocks output and terminates work');
 await page.evaluate(()=>{window.RealResultWorker=Worker;window.resultQueue=[];window.pendingResults=0;window.holdResults=true;window.Worker=function(...args){const worker=new window.RealResultWorker(...args);let listener=null;Object.defineProperty(worker,'onmessage',{configurable:true,get:()=>listener,set:fn=>{listener=fn;}});worker.addEventListener('message',event=>{if(window.holdResults){window.pendingResults++;window.heldResultSummary={ok:event.data.ok,sourceHash:event.data.receipt?.sourceSha256,bytes:event.data.buffer?.byteLength};window.resultQueue.push(()=>{listener.call(worker,event);window.pendingResults--;});}else listener.call(worker,event);});return worker;};});
 await page.locator('#session-file').setInputFiles(payload());await expect.poll(()=>page.evaluate(()=>window.pendingResults)).toBe(1);expect(await page.evaluate(()=>window.heldResultSummary)).toEqual({ok:true,sourceHash:sha(fixture),bytes:106});await page.evaluate(()=>window.holdResults=false);await load(fractional,'newer-after-result.ardour');await expect(page.locator('#error')).toContainText('FRACTIONAL_POSITION');const beforeStale=downloads;await page.evaluate(()=>window.resultQueue.splice(0).forEach(r=>r()));await expect.poll(()=>page.evaluate(()=>window.pendingResults)).toBe(0);await expect(page.locator('#error')).toContainText('FRACTIONAL_POSITION');await expect(page.locator('#file-meta')).toContainText('newer-after-result.ardour');await expect(page.locator('#rows tr')).toHaveCount(0);await expect(page.locator('#export')).toBeDisabled();await expect(page.locator('#receipt')).toBeDisabled();expect(downloads).toBe(beforeStale);await page.evaluate(()=>window.Worker=window.RealResultWorker);check('A held actual compiled-worker result cannot replace a newer invalid input or enable downloads');
 await page.locator('#sample').click();await ready();await approve();expect((await save('#export','sample-conductor.mid')).equals(expected)).toBe(true);check('Verified sample uses the same worker and exact conductor bytes');
 const privateInput=mutate('<Session version="7003"','<Session private-label="PRIVATE_BEATCOURIER_SENTINEL_74A9" version="7003"');await load(privateInput,'PRIVATE_SESSION_74A9.ardour');await ready();const offline=await save('#offline','offline-tool.html');expect(offline.toString()).not.toContain('PRIVATE_BEATCOURIER_SENTINEL_74A9');expect(offline.toString()).not.toContain('PRIVATE_SESSION_74A9');
 const reopened=await context.newPage();track(reopened);await reopened.goto(pathToFileURL(resolve(art,'offline-tool.html')).href);await expect(reopened.locator('#rows tr')).toHaveCount(0);await expect(reopened.locator('#export')).toBeDisabled();await reopened.locator('#sample').click();await expect(reopened.locator('#rows tr')).toHaveCount(10);await reopened.close();check('Clean offline copy excludes imported content and filename, then reopens with a working worker');
 await page.locator('#reset').focus();await page.keyboard.press('Enter');await expect(page.locator('#rows tr')).toHaveCount(0);await expect(page.locator('#receipt')).toBeDisabled();check('Keyboard clear removes input, review, approval and receipt');
 expect(report.workerURLs.length).toBeGreaterThan(0);expect(report.workerURLs.every(s=>s.startsWith('blob:'))).toBe(true);expect(report.pageErrors).toEqual([]);expect(report.consoleErrors).toEqual([]);expect(report.networkRequests).toEqual([]);check('Sandboxed offline main and saved pages use real blob workers with zero errors or network');report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;await shot('failure.png').catch(()=>{});await writeFile(resolve(art,'failure-dom.html'),await page.content().catch(()=>''));throw error;}finally{await writeFile(resolve(art,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await browser.close();}
