-- Fixed synthetic fixture only. Run by the official packaged ardour8-lua.
assert(Temporal.ticks_per_beat == 1920)
local source = create_session('/tmp/beatcourier-native/source', 'Source', 48000)
assert(source ~= nil and Session ~= nil)
local map = Temporal.TempoMap.write_copy()
map:set_tempo(Temporal.Tempo(120,120,4), Temporal.timepos_t.from_ticks(0))
map:set_tempo(Temporal.Tempo(100,100,4), Temporal.timepos_t.from_ticks(8*1920))
map:set_tempo(Temporal.Tempo(150,150,4), Temporal.timepos_t.from_ticks(16*1920))
map:set_meter(Temporal.Meter(3,4), Temporal.timepos_t.from_ticks(16*1920))
Temporal.TempoMap.update(map)
map=nil
assert(Session:save_state('',false,false,false,false,false)==0)
close_session()
local target=create_session('/tmp/beatcourier-native/target','Target',48000)
assert(target ~= nil and Session ~= nil)
assert(Temporal.TempoMap.read():quarters_per_minute_at(Temporal.timepos_t.from_ticks(0))==120)
assert(Session:save_state('',false,false,false,false,false)==0)
close_session()
print('BEATCOURIER_NATIVE_AUTHOR_FINISHED')
