import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const worker=await build({entryPoints:['web/worker.mjs'],bundle:true,write:false,format:'iife',target:'es2022',minify:true,legalComments:'inline'});
const sample=await readFile('test/fixtures/expanded-native.ardour','utf8');
const app=await build({entryPoints:['web/app.mjs'],bundle:true,write:false,format:'iife',target:'es2022',minify:true,legalComments:'inline',define:{WORKER_SOURCE:JSON.stringify(worker.outputFiles[0].text),SAMPLE_XML:JSON.stringify(sample)}});
const css=await readFile('web/styles.css','utf8'),notices=await readFile('THIRD_PARTY_NOTICES.txt','utf8');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const html=(await readFile('web/index.html','utf8')).replace('/* APP_CSS */',()=>css).replace('/* THIRD_PARTY */',()=>escape(notices)).replace('/* APP_JS */',()=>app.outputFiles[0].text.replace(/<\/script/gi,'<\\/script'));
if(/\/\* (APP_CSS|THIRD_PARTY|APP_JS) \*\//.test(html))throw Error('Unfilled standalone template');
await mkdir('dist',{recursive:true});await writeFile('dist/beat-courier.html',html);console.log('Standalone HTML',Buffer.byteLength(html),'bytes');
